# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

pod 'AFNetworking'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'Mantle'
pod 'Masonry'

target 'XCF' do

end

